name: ðŸ¤–+ðŸ+ðŸ§+ðŸŽ+ðŸªŸ Assemble export templates
on:
  workflow_call:
    inputs:
      godot-kotlin-jvm-version:
        type: string
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-export_templates_assemble
  cancel-in-progress: true

jobs:
  create-export-templates-tpz:
    runs-on: ubuntu-20.04
    name: Create export template tpz
    steps:
      - name: Create templates folder
        run: mkdir templates
        shell: bash

      - name: Download android export templates
        uses: actions/download-artifact@v3
        with:
          name: export_template_android_all
          path: android_templates/

      - name: Copy android export templates
        shell: bash
        run: |
          cp android_templates/android_source.zip templates/android_source.zip
          cp android_templates/android_debug.apk templates/android_debug.apk
          cp android_templates/android_release.apk templates/android_release.apk

      - name: Download ios debug export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_all_ios
          path: templates/ios.zip

      - name: Download linux x86_64 debug export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_debug_linux_x86_64
          path: templates/linux_debug.x86_64

      - name: Download linux x86_64 release export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_release_linux_x86_64
          path: templates/linux_release.x86_64

      - name: Download windows x86_64 debug export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_debug_windows_x86_64
          path: templates/windows_debug_x86_64.exe

      - name: Download windows x86_64 release export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_release_windows_x86_64
          path: templates/windows_release_x86_64.exe

      - name: Download macos debug export template
        uses: actions/download-artifact@v3
        with:
          name: export_template_all_macos
          path: templates/macos.zip

      - name: Create version.txt
        run: |
          refVersion=${{ inputs.godot-version }}
          templatesVersion=${refVersion//-/.} #replace `-` with `.` in templates version
          echo "$templatesVersion" > templates/version.txt
        shell: bash

      - name: Compress templates folder to tpz
        run: zip -r godot-kotlin-jvm_export_templates_${{ inputs.godot_kotlin_jvm_version }}.tpz templates
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-kotlin-jvm_export_templates_${{ inputs.godot_kotlin_jvm_version }}.tpz
          path: godot-kotlin-jvm_export_templates_${{ inputs.godot_kotlin_jvm_version }}.tpz