name: üçè Assemble iOS
on:
  workflow_call:
    inputs:
      godot-kotlin-jvm-version:
        type: string
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios_assemble
  cancel-in-progress: true

jobs:
  create-ios-export-template-universal:
    runs-on: macos-13 #MoltenVK is built differently if using macos-14+
    name: Assemble iOS export template
    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      # Python must be kept below 3.12
      #https://github.com/KhronosGroup/MoltenVK/blob/3b9e335fe8fc8a72cf6099acbd54128889445c0a/.github/workflows/CI.yml#L44
      - name: Setup python and scons
        uses: ./.github/actions/godot-deps
        with:
          python-version: 3.11

      - name: Download ios export template binaries
        uses: actions/download-artifact@v4
        with:
          name: export_template_ios_all
          path: "./"

      - name: Clone MoltenVK
        uses: actions/checkout@v4
        with:
          repository: KhronosGroup/MoltenVK
          path: MoltenVk
          ref: v1.2.10

      - name: Build MoltenVK
        run: |
          cd MoltenVK && ./fetchDependencies --ios && make ios

      - name: Create iOS template app
        run: |
          cp -r misc/dist/ios_xcode .
          cp -r MoltenVK/Package/Release/MoltenVK/MoltenVK.xcframework ios_xcode/
          cp libgodot.ios.template_release.arm64.a ios_xcode/libgodot.ios.release.xcframework/ios-arm64/libgodot.a
          cp libgodot.ios.template_debug.arm64.a ios_xcode/libgodot.ios.debug.xcframework/ios-arm64/libgodot.a
          mv ios_xcode/ ios/ && cd ios/
          zip -q -9 -r export_template_all_ios.zip .

      - name: Upload iOS template app
        uses: actions/upload-artifact@v4
        with:
          name: export_template_all_ios
          path: ios/export_template_all_ios.zip
