name: üçé macOS Builds
on:
  workflow_call:
    inputs:
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos_build
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-14
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build editor release x86_64 (target=editor)
            cache-name: editor_release_macos_x86_64
            target: editor
            sconsflags: arch=x86_64

          - name: Build editor debug x86_64 (target=editor, debug_symbols=true )
            cache-name: editor_debug_macos_x86_64
            target: editor
            sconsflags: arch=x86_64 debug_symbols=true

          - name: Build editor dev x86_64 (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: editor_dev_macos_x86_64
            target: editor
            sconsflags: arch=x86_64 dev_build=yes debug_symbols=true

          - name: Build release template x86_64
            cache-name: export_template_release_macos_x86_64
            target: template_release
            sconsflags: arch=x86_64

          - name: Build debug template x86_64
            cache-name: export_template_debug_macos_x86_64
            target: template_debug
            sconsflags: arch=x86_64

          - name: Build editor release arm64 (target=editor)
            cache-name: editor_release_macos_arm64
            target: editor
            sconsflags: arch=arm64

          - name: Build editor debug arm64 (target=editor, debug_symbols=true )
            cache-name: editor_debug_macos_arm64
            target: editor
            sconsflags: arch=arm64 debug_symbols=true

          - name: Build editor dev arm64 (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: editor_dev_macos_arm64
            target: editor
            sconsflags: arch=arm64 dev_build=yes debug_symbols=true

          - name: Build release template arm64
            cache-name: export_template_release_macos_arm64
            target: template_release
            sconsflags: arch=arm64

          - name: Build debug template arm64
            cache-name: export_template_debug_macos_arm64
            target: template_debug
            sconsflags: arch=arm64

    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
        with:
          path: modules/kotlin_jvm

      - name: Setup Godot build cache
        uses: ./modules/kotlin_jvm/.github/actions/cache
        with:
          key: ${{ matrix.cache-name }}
          path: "${{github.workspace}}/.scons-cache/"
          s3-host: ${{ secrets.S3_HOST }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-user: ${{ secrets.S3_USER }}
          s3-password: ${{ secrets.S3_PASSWORD }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      ##Switch back to the official Godot script when we switch to the next official stable version.
      - name: Setup Vulkan SDK
        run: |
          sh ./modules/kotlin_jvm/install_vulkan_sdk_macos.sh

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ matrix.sconsflags }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cache-name }}
          path: "bin/*"
