name: üçé macOS Builds
on:
  workflow_call:
    inputs:
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos_build
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build editor release x86_64 (target=editor)
            cache-name: editor_release_macos_x86_64
            target: editor
            sconsflags: arch=x86_64

          - name: Build editor debug x86_64 (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: editor_debug_macos_x86_64
            target: editor
            sconsflags: arch=x86_64 dev_build=yes debug_symbols=true

          - name: Build release template x86_64
            cache-name: export_template_release_macos_x86_64
            target: template_release
            sconsflags: arch=x86_64

          - name: Build debug template x86_64
            cache-name: export_template_debug_macos_x86_64
            target: template_debug
            sconsflags: arch=x86_64

          - name: Build editor release arm64 (target=editor)
            cache-name: editor_release_macos_arm64
            target: editor
            sconsflags: arch=arm64

          - name: Build editor debug arm64 (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: editor_debug_macos_arm64
            target: editor
            sconsflags: arch=arm64 dev_build=yes debug_symbols=true

          - name: Build release template arm64
            cache-name: export_template_release_macos_arm64
            target: template_release
            sconsflags: arch=arm64

          - name: Build debug template arm64
            cache-name: export_template_debug_macos_arm64
            target: template_debug
            sconsflags: arch=arm64

    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      # TODO: remove once on godot 4.2.2 or newer!
      - name: Cherry pick macos fix
        run: |
          git fetch -a
          git config --global user.email "mario@super.com"
          git config --global user.name "Super Mario"
          git cherry-pick a2c1c01941a3dec3e2a361d9dc21bb0390efcbaf

      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
        with:
          path: modules/kotlin_jvm

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ matrix.sconsflags }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
