name: Check PR - Engine Export Template Debug
on: [pull_request]

env:
  SCONS_CACHE_MSVC_CONFIG: true
  GODOT_BASE_VERSION: 3.2.3

jobs:
  build-export-debug:
    strategy:
      matrix:
        name: [ Linux, OSX, Windows, Android ]
        include:
          - name: Linux
            os: ubuntu-latest
            platform: x11
          - name: OSX
            os: macos-latest
            platform: osx
          - name: Windows
            os: windows-latest
            platform: windows
          - name: Android
            os: ubuntu-latest
            platform: android
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure dependencies
        if: matrix.platform == 'x11'
        run: |
          sudo apt-get update && sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.2.3-stable
      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive
      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        if: matrix.platform != 'android'
        id: template-debug-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/${{matrix.platform}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}
      - name: Load .scons_cache directory for Android armv7
        if: matrix.platform == 'android'
        id: template-debug-cache-android-armv7
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/${{matrix.platform}}/armv7/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}
      - name: Load .scons_cache directory for Android arm64-v8
        if: matrix.platform == 'android'
        id: template-debug-cache-android-arm64-v8
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/${{matrix.platform}}/arm64-v8/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_VERSION}}
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
      - name: Set up JDK 1.8
        if: matrix.platform == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v2
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Build debug export template
        if: matrix.platform != 'android'
        env:
          SCONS_CACHE: ${{github.workspace}}/${{matrix.platform}}/.scons_cache/
        run: |
          scons platform=${{ matrix.platform }} tools=no target=release_debug bits=64 -j${{ steps.cpu-cores.outputs.count }}
      - name: Build android debug binary armv7
        if: matrix.platform == 'android'
        env:
          SCONS_CACHE: ${{github.workspace}}/${{matrix.platform}}/armv7/.scons_cache/
        run: |
          scons platform=${{ matrix.platform }} target=release_debug android_arch=armv7 -j${{ steps.cpu-cores.outputs.count }}
      - name: Build android debug binary arm64v8
        if: matrix.platform == 'android'
        env:
          SCONS_CACHE: ${{github.workspace}}/${{matrix.platform}}/arm64-v8/.scons_cache/
        run: |
          scons platform=${{ matrix.platform }} target=release_debug android_arch=arm64v8 -j${{ steps.cpu-cores.outputs.count }}
      - name: Build android debug export template
        if: matrix.platform == 'android'
        run: |
          cd platform/android/java/ && ./gradlew generateGodotTemplates
