name: Check PR - Entry Generator

on:
  pull_request:
    paths:
      - 'kt/entry-generation/godot-entry-generator/**'

jobs:
  build_entry_generator:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 4.1.3-stable
      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build entry-generator
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: modules/kotlin_jvm/kt/
          build-root-directory: modules/kotlin_jvm/kt/
          arguments: godot-entry-generator:build
