name: Dev test deployment

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-trigger_dev_test_deployment
  cancel-in-progress: true

jobs:
  deploy-jvm:
    name: Deploy jvm artifacts
    runs-on: ubuntu-latest
    env:
      GODOT_KOTLIN_GPG_PRIVATE_KEY_ASCII: ${{ secrets.GODOT_KOTLIN_GPG_PRIVATE_KEY_ASCII }}
      GODOT_KOTLIN_GPG_KEY_PASSPHRASE: ${{ secrets.GODOT_KOTLIN_GPG_KEY_PASSPHRASE }}
      GODOT_KOTLIN_MAVEN_CENTRAL_PORTAL_TOKEN_USERNAME: ${{ secrets.GODOT_KOTLIN_MAVEN_CENTRAL_PORTAL_TOKEN_USERNAME }}
      GODOT_KOTLIN_MAVEN_CENTRAL_PORTAL_TOKEN_PASSWORD: ${{ secrets.GODOT_KOTLIN_MAVEN_CENTRAL_PORTAL_TOKEN_PASSWORD }}
#      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
#      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
#      GODOT_KOTLIN_INTELLIJ_PLUGIN_PUBLISH: ${{secrets.GODOT_KOTLIN_INTELLIJ_PLUGIN_PUBLISH }}
    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
        with:
          path: modules/kotlin_jvm

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

#      - name: Publish common
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :common:publish
#
#      - name: Publish tools-common
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :tools-common:publish
#
#      - name: Publish godot-build-props
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-build-props:publish
#
#      - name: Publish godot-entry-generator
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-entry-generator:publish
#
#      - name: Publish godot-kotlin-symbol-processor
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-kotlin-symbol-processor:publish
#
#      - name: Publish godot-internal-library debug
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-internal-library:publish -Pdebug
#
#      - name: Publish godot-internal-library release
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-internal-library:publish -Prelease
#
#      - name: Publish godot-core-library debug
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-core-library:publish -Pdebug
#
#      - name: Publish godot-core-library release
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-core-library:publish -Prelease
#
#      - name: Publish godot-api-library debug
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-api-library:publish -Pdebug
#
#      - name: Publish godot-api-library release
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-api-library:publish -Prelease
#
#      - name: Publish godot-extension-library debug
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-extension-library:publish -Pdebug
#
#      - name: Publish godot-extension-library release
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-extension-library:publish -Prelease
#
#      - name: Publish godot-coroutine-library debug
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-coroutine-library:publish -Pdebug
#
#      - name: Publish godot-coroutine-library release
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-coroutine-library:publish -Prelease

      - name: Publish godot-plugins-common
        shell: sh
        run: |
          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-plugins-common:publish

#      - name: Publish godot plugins
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-gradle-plugin:publish :godot-gradle-plugin:publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
#
#      - name: Deploy intellij plugin
#        shell: sh
#        run: |
#          modules/kotlin_jvm/kt/gradlew -p modules/kotlin_jvm/kt/ :godot-intellij-plugin:publishPlugin